Update httpd init script

diff --git a/board/abacus/rpi2/overlay_aroio/etc/init.d/httpd b/board/abacus/rpi2/overlay_aroio/etc/init.d/httpd
--- a/board/abacus/rpi2/overlay_aroio/etc/init.d/httpd
+++ b/board/abacus/rpi2/overlay_aroio/etc/init.d/httpd
@@ -1,7 +1,39 @@
 #!/bin/sh
 
-. /mnt/mmcblk0p1/userconfig.txt
+NAME=httpd
+DAEMON=/usr/sbin/httpd
+PIDFILE=/var/run/$NAME.pid
+DAEMON_ARGS="-h /opt/www -c /etc/httpd.conf"
 
-echo -e '*.php:/usr/bin/php-cgi\n/:aroio:'"$USERPASSWD" > /etc/httpd.conf
+. /etc/aroio/userconfig
 
-httpd -h /opt/www -c /etc/httpd.conf
+start() {
+    printf "Starting $NAME: "
+    echo -e '*.php:/usr/bin/php-cgi\n/:aroio:'"$USERPASSWD" > /etc/httpd.conf
+    start-stop-daemon --make-pidfile -p$PIDFILE --start --quiet --background --exec "$DAEMON" \
+                      -- $DAEMON_ARGS \
+        && echo "OK" || echo "FAIL"
+}
+
+stop() {
+        printf "Stopping $NAME: "
+        start-stop-daemon --stop --quiet --pidfile $PIDFILE \
+                && echo "OK" || echo "FAIL"
+}
+
+case "$1" in
+        start)
+                start
+                ;;
+        stop)
+                stop
+                ;;
+        restart)
+                stop
+                sleep 1
+                start
+                ;;
+        *)
+                echo "Usage: $0 {start|stop|restart}"
+                exit 1
+esac
