Implement shairport config dependend startup sequence

diff --git a/board/abacus/rpi2/overlay_aroio/etc/init.d/shairport b/board/abacus/rpi2/overlay_aroio/etc/init.d/shairport
--- a/board/abacus/rpi2/overlay_aroio/etc/init.d/shairport
+++ b/board/abacus/rpi2/overlay_aroio/etc/init.d/shairport
@@ -1,17 +1,45 @@
 #!/bin/sh
 
+. /etc/aroio/userconfig
+. /opt/shutils.sh
+
 NAME=shairport
-USER=shairport
-GROUP=shairport
-DAEMON=/usr/bin/shairport-sync
 PIDFILE=/var/run/$NAME.pid
-DAEMON_ARGS="-d"
 
 start() {
-        printf "Starting $NAME: "
-        start-stop-daemon -c $USER:$GROUP --make-pidfile -p$PIDFILE --start --quiet --background --exec "$DAEMON" \
+    ETHADDR=$(ethaddr)
+    WLANADDR=$(wlanaddr)
+    until ! [ "$ETHADDR" = "" ] || ! [ "$WLANADDR" = "" ]
+    do
+	echo "Shairport:   Network not available, waiting..."
+	sleep 2
+	ETHADDR=$(ethaddr)
+	WLANADDR=$(wlanaddr)
+    done
+    if [ "$DEBUG" = "ON" ] ; then
+	touch /var/log/shairportlog.txt
+    fi
+
+    if [ "$BRUTEFIR" = "OFF" ] ; then
+	PLAYER="shairport-sync"
+	if [ "$MSCODING" = "ON" ] ; then
+	    OUTPUT=" -o alsa -- -d mscoded"
+	else 	OUTPUT=" -o alsa -- -d stereo"
+	fi
+    else
+	PLAYER="shairport-sync"
+	OUTPUT=" -o jack -- brutefir"
+    fi
+
+    DAEMON=/usr/bin/$PLAYER
+
+    DAEMON_ARGS="-d -m avahi -v -w -B /usr/bin/shairport-sync-startaction -E /usr/bin/shairport-sync-stopaction \
+	-a "$PLAYERNAME" $OUTPUT "
+    printf "Starting $NAME: "
+    clogn "$(basename $DAEMON) cmdline: $DAEMON $DAEMON_ARGS"
+    start-stop-daemon --make-pidfile -p$PIDFILE --start --quiet --exec "$DAEMON" \
                 -- $DAEMON_ARGS \
-                && echo "OK" || echo "FAIL"
+        && echo "OK" || echo "FAIL"
 }
 
 stop() {
