Revert "Use logging for squeezelite init script"
Redirect to log file in rcS instead.

This reverts commit 07747b848c9f1edc368ea1f0ce23924a8a684627.

diff --git a/board/abacus/rpi2/overlay_aroio/etc/init.d/squeezelite b/board/abacus/rpi2/overlay_aroio/etc/init.d/squeezelite
--- a/board/abacus/rpi2/overlay_aroio/etc/init.d/squeezelite
+++ b/board/abacus/rpi2/overlay_aroio/etc/init.d/squeezelite
@@ -1,42 +1,23 @@
 #!/bin/sh
 
-. /etc/aroio/userconfig
-
-. /opt/shutils.sh
-
 NAME=squeezelite
 USER=squeezelite
 GROUP=squeezelite
 DAEMON=/usr/bin/squeezelite
 PIDFILE=/var/run/$NAME.pid
-DAEMON_ARGS="-M AroioEX -p 99 -z"
-
+DAEMON_ARGS="-M AroioEX"
 
 start() {
-    cmark
-    clog -n "Starting $NAME: "
-    ALSAPARAMS="-a 8192:1024:32:0 -b 1024:8192"
-    RATE=""
-    RESAMPLE=""
-    if [ "$MSCODING" = "ON" ]
-    then
-	OUTPUT="-o mscoded"
-	clog -n " (Output is MS-coded!) "
-    else
-	OUTPUT="-o plughw:0,0"
-	clog -n " (Output is stereo!) "
-    fi
-    DAEMON_ARGS="$DAEMON_ARGS $ALSAPARAMS $OUTPUT"
-    start-stop-daemon -c $USER:$GROUP --make-pidfile -p$PIDFILE --start --quiet --exec "$DAEMON" \
-                      -- $DAEMON_ARGS \
-        && clog "OK" || clog "FAIL"
-    clogn "squeezelite cmdline: $DAEMON $DAEMON_ARGS"
+        printf "Starting $NAME: "
+        start-stop-daemon -c $USER:$GROUP --make-pidfile -p$PIDFILE --start --quiet --background --exec "$DAEMON" \
+                -- $DAEMON_ARGS \
+                && echo "OK" || echo "FAIL"
 }
 
 stop() {
-        clog -n "Stopping $NAME: "
+        printf "Stopping $NAME: "
         start-stop-daemon --stop --quiet --pidfile $PIDFILE \
-                && clog "OK" || clog "FAIL"
+                && echo "OK" || echo "FAIL"
 }
 
 case "$1" in
